import '../globals.css'
import { Inter } from 'next/font/google'
import Nav from '../../components/nav/page'
import Footer from '../../components/footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=' p-0 m-0'>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
